export enum Genre {
  Crime = 'Crime',
  Drama = 'Drama',
  Biography = 'Biography',
  Comedy = 'Comedy',
  Adventure = 'Adventure',
  Family = 'Family',
  Fantasy = 'Fantasy',
  Action = 'Action',
  Thriller = 'Thriller',
  Animation = 'Animation',
  FilmNoir = 'Film-Noir',
  Mystery = 'Mystery',
  Romance = 'Romance',
  Music = 'Music',
  SciFi = 'Sci-Fi',
  War = 'War',
  Western = 'Western',
}
